name: Build Multiarch and push to DockerHub

on:
  push:
    branches: 7.x-1.x
    tags: 7.x-1.*

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get version tag
        run: echo ::set-output name=VERSION_TAG::${GITHUB_REF#refs/tags/}
      - 
        name: print version tag
        run: echo ${{ env.VERSION_TAG  }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: docker
      #     file: ./docker/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       raleonardo/farmos:latest

